weights: yolo-facev2s-preweight.pt
cfg: ''
data: fire_smoke_new/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 150
batch_size: 16
img_size:
- 640
- 640
nofrozen: false
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\exp8
total_batch_size: 16
